### ISSUE TITLE
Things are all backwards for touch 

### ISSUE THREAD

**Issue by goose2000** [nift4/Raspberry-Pi-Testing#1]
Hi, I have been running sdlkit.py on my capacitive 2.8" screen, but the axis for the touchscreen is reversed (mouse is all backwards). Is there some other place this is configured in pigamemui ?

My config.txt uses these lines to get it configured and running fine with other .py scripts:

dtoverlay=pitft28-capacitive,speed=32000000,fps=25,touch-swapxy,touch-invx

**Comment by nift4** [comment]
Hi,
first to say: I don't have any lines in my config.txt. I don't know about them. But without the lines I can give you assistance :)
It's okay to try without lines?

**Comment by nift4** [comment]
I have a way to set rotation in driver, but only 90° and 270° are supported. In all other scripts except sdlkit.py you can test it in `pigame.init(90)` or `pigame.init(270)`(instead of default `pigame.init()`). Please reply if you found the right value.

**Comment by BroMarduk** [comment]
@goose2000  Did you configure your pi with the Adafruit script?   What orientation are you using?  I've seen some configurations do some axis swapping to align better with pygame.

**Comment by goose2000** [comment]
Ok, I have had some success tonight! I started with a fresh STRETCH-lite SD and did run the Adafruit script. I had it set to 270 landscape; cables come out the top physical orientation (PiZero W).

I then started on all the dependencies needed (and moving some things into the right dir) and I wound up with test.py and sdlykit.py working nicely!

I did get an error on sdl.py - but that I can see is a different issue, may do another report for that? Think it's easy one : 

` File "sdl.py", line 12, in <module>
    pigame.init()
AttributeError: module 'pigame' has no attribute 'init'`

And yeah pigame.py doesn't have any initialization definition like
def __init__(self):
 
Watch you guys all week, on the other ticket -  thanks a bunch for this work/modules - I'm trying to make a HDMI touchscreen switcher with LibCEC and cec-client

**Comment by BroMarduk** [comment]
@goose2000 It looks like @nift4 moved the classed based version of the module with button support to master, which will require a change to sdl.py.

Try changing or creating a new sdl.py to this and run:

```

import pygame,pigame
from pygame.locals import *
import os
from time import sleep
#Colours
WHITE = (255,255,255)
os.putenv('SDL_FBDEV', '/dev/fb1')
os.putenv('SDL_MOUSEDRV','dummy')
os.putenv('SDL_MOUSEDEV','/dev/null')

pygame.init()
pygame.mouse.set_visible(True)
lcd = pygame.display.set_mode((320, 240))
lcd.fill((0,0,0))
pygame.display.update()

font_big = pygame.font.Font(None, 45)

touch_buttons = {'Shutdown':(80,60), 'Quit':(240,60), '17 off':(80,180), '4 off':(240,180)}

for k,v in touch_buttons.items():
    text_surface = font_big.render('%s'%k, True, WHITE)
    rect = text_surface.get_rect(center=v)
    lcd.blit(text_surface, rect)

pygame.display.update()
try:
    mygame = pigame.PiTft()
    while True:
        mygame.update()
        # Scan touchscreen events
        for event in pygame.event.get():
            if(event.type is MOUSEBUTTONDOWN):
                x,y = pygame.mouse.get_pos()
                print(x,y)
            elif(event.type is MOUSEBUTTONUP):
                x,y = pygame.mouse.get_pos()
                print(x,y)
                #Find which quarter of the screen we're in
                if y > 120:
                    if x < 160:
                        print("17off")
                    else:
                        print("4off")
                else:
                    if x < 160:
                        os.system("sudo poweroff")
                    else:
                        import sys
                        sys.exit(0)
        sleep(0.1)
except KeyboardInterrupt:
    pass
finally:
   del mygame
```

Also, if you haven't already I'd recommend grabbing the latest pitft-touchscreen from either https://github.com/przemof/pitft_touchscreen or  https://github.com/pigamedrv/pitft_touchscreen.

**Comment by goose2000** [comment]
@BroMarduk - that fixed the example! Might want to commit that. And did grab the updated repo of pitft_touchscreen. So I have only used the Adafruit script and these modules/scripts and got all to work, no hacks in my config.txt and no downgrade to the SDL1.2 the old Adafruit pages talk about.

**Comment by nift4** [comment]
Yup. Thanks @BroMarduk for the help to @goose2000
