### ISSUE TITLE
Trouble getting anything to work

### ISSUE THREAD

**Issue by gmeader** [nift4/Raspberry-Pi-Testing#3]
I'm a very new Python user, so please don't assume I know anything.
I am trying to use your tests on my Pi with Adafruit 2.3" capacitive touchscreen.

I cloned Raspberry-Pi-Testing
**I read the README Requirements**

- I cloned PiTFT_Screen
- I cloned pitft_touchscreen
- I cloned pigame
- I installed evdev
- I installed python3-pygame
- I cloned pigameui and ran setup.py install

sudo python3 Raspberry-Pi-Testing/sdlkit.py gives: **ImportError: No module named 'pitft_touchscreen'** 
sudo puthon3 Raspberry-Pi-Testing/sdl.py gives: **ImportError: No module named 'pigame'** 
sudo python3 Raspberry-Pi-Testing/test.py gives: **ImportError: No module named 'pitftscreen'**

**What do I need to do to get this to work?**
Thanks for your help, I know these are newbie questions...
gmeader@gmail.com

**Comment by nift4** [comment]
2.3" capactive?? Exists that? I only found 3.5" RESISTIVE 2.8" CAPACITIVE 2.8" RESISTIVE and 3.2" RESISTIVE that you could mean.
For sdl.py and test.py it's a simple error. You'll need the .py files named `pitft_touchscreen.py` `pigame.py` `pitftscreen.py` in the directory of `sdl.py` and `test.py`. And I run the scripts always inside of `Raspberry-Pi-Testing/`. I don't know if it's makes a difference but you can try it out. For sdlkit.py I'm looking... `pigameui` has the files included. P.S.: Bad English included :)

**Comment by gmeader** [comment]
,I'm seeing that pigame.py is doing **import pygame,pitft_touchscreen**

But it can't find pitft_touchscreen

(pip installed pygame OK)

So it looks like there needs to b e a way to **install** or **pip** pitft_touchscreen in the right place so python can find it.

I guess for now it will just copy pitft_touchscreen into directories where it fails to import?

**Comment by nift4** [comment]
Yes. And look at the edit.

**Comment by nift4** [comment]
Works https://github.com/pigamedrv/pigameui/commit/d6ffe6e89f5d95200411412b37cec3923b8e76b0 for you in sdlkit.py?

**Comment by gmeader** [comment]
I copied pigame.py,  pitftscreen.py, and  pitft_touchscreen.py into the Raspberry-Pi-Testing directory.
Now test.py works.
sdl.py works (but my X and Y axis of the touch screen are swapped)

**sdlkit.py crashes** with:

Traceback (most recent call last):
  File "sdlkit.py", line 55, in <module>
    ui.run()
  File "/usr/local/lib/python3.5/dist-packages/pygameui-0.2.3-py3.5.egg/pygameui/__init__.py", line 102, in run
  File "/usr/local/lib/python3.5/dist-packages/pygameui-0.2.3-py3.5.egg/pygameui/__init__.py", line 114, in single_loop_run
UnboundLocalError: local variable 'pitft' referenced before assignment

**Comment by nift4** [comment]
Works sdlkit.py now?

**Comment by gmeader** [comment]
No sdlkit.py does not work.

**sdlkit.py crashes** with:

Traceback (most recent call last):
File "sdlkit.py", line 55, in 
ui.run()
File "/usr/local/lib/python3.5/dist-packages/pygameui-0.2.3-py3.5.egg/pygameui/**init**.py", line 102, in run
File "/usr/local/lib/python3.5/dist-packages/pygameui-0.2.3-py3.5.egg/pygameui/**init**.py", line 114, in single_loop_run
UnboundLocalError: local variable 'pitft' referenced before assignment

**Comment by nift4** [comment]
Has you pulled/recloned the git repo of pigameui and ran `sudo python3 setup.py`?

**Comment by nift4** [comment]
@gmeader

**Comment by gmeader** [comment]
I started from scratch with a new Raspbian-stretch-lite and ran the adafruit PiTFT installer script

**I installed pigameui:**
```
git clone https://github.com/nift4/pigameui.git
cd pigameui
sudo python3 setup.py install
```
**I tried to run /test.py but got an error about evdev, even though I had done pip3 install evdev**
```
pi@raspberrypi:~/pigameui/bin $ pip3 install evdev
Collecting evdev
  Using cached https://www.piwheels.org/simple/evdev/evdev-1.1.2-cp35-cp35m-linux_armv7l.whl
Installing collected packages: evdev
Successfully installed evdev-1.1.2
pi@raspberrypi:~/pigameui/bin $ sudo python3 test.py
pip3 install evdev
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/pygameui-0.2.3-py3.5.egg/pygameui/pitft_touchscreen.py", line 6, in <module>
ImportError: No module named 'evdev'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    import pygameui as ui
  File "/usr/local/lib/python3.5/dist-packages/pygameui-0.2.3-py3.5.egg/pygameui/__init__.py", line 41, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pygameui-0.2.3-py3.5.egg/pygameui/pigame.py", line 2, in <module>
  File "/usr/local/lib/python3.5/dist-packages/pygameui-0.2.3-py3.5.egg/pygameui/pitft_touchscreen.py", line 9, in <module>
ImportError: evdev not found
pi@raspberrypi:~/pigameui/bin $
```
Attached is a PDF showing all the install steps I did
[Installing_Pigameui.pdf](https://github.com/nift4/Raspberry-Pi-Testing/files/2878434/Installing_Pigameui.pdf)

**Comment by nift4** [comment]
@gmeader

`pip3 install evdev` installs it for `pi`, but it must be installed for `root` with `sudo pip3 install evdev`, `sudo` is the important thing for this error.

**Comment by gmeader** [comment]
Thanks for the help. pigameui/bin/test.py now works!
I now have complete directions for successfully installing pigameui from scratch on a new Raspbian-lite installation. (see the above PDF - but use **sudo** when invoking pip3

**Comment by nift4** [comment]
Can it closed @gmeader?

**Comment by gmeader** [comment]
Yes close this.
